[package]
name = "bread-content"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0.1", features = ["display"] }
sysinfo = { version = "0.37.2", default-features = false, features = ["system"] }
time-format = "1.2.2"

[features]
default = []
timing = []
